//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_CheckIn
    {
        public int Id { get; set; }
        public int GuestId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string GRCNo { get; set; }
        public int PurposeId { get; set; }
        public int PlanId { get; set; }
        public int CompanyId { get; set; }
        public int AgentId { get; set; }
        public string Comments { get; set; }
        public int UserId { get; set; }
    
        public virtual HMS_Agent HMS_Agent { get; set; }
        public virtual HMS_Company HMS_Company { get; set; }
        public virtual HMS_Guest HMS_Guest { get; set; }
        public virtual HMS_Plan HMS_Plan { get; set; }
        public virtual HMS_Purpose HMS_Purpose { get; set; }
        public virtual HMS_Room HMS_Room { get; set; }
    }
}
