//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HMS_Room()
        {
            this.HMS_CheckIn = new HashSet<HMS_CheckIn>();
        }
    
        public int Id { get; set; }
        public string RoomNo { get; set; }
        public int FloorId { get; set; }
        public int RoomTypeId { get; set; }
        public int StatusId { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HMS_CheckIn> HMS_CheckIn { get; set; }
        public virtual HMS_Floor HMS_Floor { get; set; }
        public virtual HMS_RoomType HMS_RoomType { get; set; }
        public virtual Status Status { get; set; }
    }
}
