//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_AdvanceControl
    {
        public int Id { get; set; }
        public int OutletId { get; set; }
        public int RecieptNo { get; set; }
        public bool PrintAdvance { get; set; }
        public int NoofCopies { get; set; }
        public bool SendSms { get; set; }
        public bool SmsToMd { get; set; }
        public bool SmsToGuest { get; set; }
        public bool SendEmail { get; set; }
        public bool EmailToMd { get; set; }
        public bool EmailToGuest { get; set; }
    
        public virtual HMS_Outlet HMS_Outlet { get; set; }
    }
}
