//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_TaxControl
    {
        public int Id { get; set; }
        public int OutletId { get; set; }
        public string TaxName { get; set; }
        public string TaxNo { get; set; }
        public int FromSlabAmount { get; set; }
        public int ToSlabAmount { get; set; }
        public int Percentage { get; set; }
        public bool Active { get; set; }
    
        public virtual HMS_Outlet HMS_Outlet { get; set; }
    }
}
