//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMS_Rate
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int PlanId { get; set; }
        public int RoomTypeId { get; set; }
        public int Occupancy { get; set; }
        public int Amount { get; set; }
        public int ExtraPersonCharge { get; set; }
        public string AgentName { get; set; }
        public string PlanName { get; set; }
        public string RoomType { get; set; }
    }
}
